title: Just the Docs Template
description: Your site description
theme: just-the-docs

url: https://mrau66.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
